
package org.donstu.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WorkshopService", targetNamespace = "https://donstu.org/workshop")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WorkshopService {


    /**
     * 
     * @return
     *     returns java.util.List<org.donstu.client.Master>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMasters", targetNamespace = "https://donstu.org/workshop", className = "org.donstu.client.GetMasters")
    @ResponseWrapper(localName = "getMastersResponse", targetNamespace = "https://donstu.org/workshop", className = "org.donstu.client.GetMastersResponse")
    @Action(input = "https://donstu.org/workshop/WorkshopService/getMastersRequest", output = "https://donstu.org/workshop/WorkshopService/getMastersResponse")
    public List<Master> getMasters();

}
