
package org.donstu.async;

import java.util.List;
import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WorkshopService", targetNamespace = "https://donstu.org/workshop")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WorkshopService {


    /**
     * 
     * @return
     *     returns javax.xml.ws.Response<org.donstu.async.GetMastersResponse>
     */
    @WebMethod(operationName = "getMasters")
    @RequestWrapper(localName = "getMasters", targetNamespace = "https://donstu.org/workshop", className = "org.donstu.async.GetMasters")
    @ResponseWrapper(localName = "getMastersResponse", targetNamespace = "https://donstu.org/workshop", className = "org.donstu.async.GetMastersResponse")
    public Response<GetMastersResponse> getMastersAsync();

    /**
     * 
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getMasters")
    @RequestWrapper(localName = "getMasters", targetNamespace = "https://donstu.org/workshop", className = "org.donstu.async.GetMasters")
    @ResponseWrapper(localName = "getMastersResponse", targetNamespace = "https://donstu.org/workshop", className = "org.donstu.async.GetMastersResponse")
    public Future<?> getMastersAsync(
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetMastersResponse> asyncHandler);

    /**
     * 
     * @return
     *     returns java.util.List<org.donstu.async.Master>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMasters", targetNamespace = "https://donstu.org/workshop", className = "org.donstu.async.GetMasters")
    @ResponseWrapper(localName = "getMastersResponse", targetNamespace = "https://donstu.org/workshop", className = "org.donstu.async.GetMastersResponse")
    @Action(input = "https://donstu.org/workshop/WorkshopService/getMastersRequest", output = "https://donstu.org/workshop/WorkshopService/getMastersResponse")
    public List<Master> getMasters();

}
